default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: misbah
  password: Harrypotter@08
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: rails-sample-guestbook-master_development

test:
  <<: *default
  database: rails-sample-guestbook-master_test

production:
  <<: *default
  database: rails-sample-guestbook-master_production